### ISSUE TITLE
странные какие-то ответы..

### ISSUE THREAD

**Issue by nais2008** [shauru1118/webservice#2]
![image](https://github.com/user-attachments/assets/a0926e7e-3e99-47bc-89d7-b985b83e9e3c)
И как понять в чем ошибка...

**Comment by shauru1118** [comment]
Моя программа возвращает только {"error":"...", и там написано, что введено неправильное выражение, проверь его. Так же все расшифровки написаны в README, посмотри там.

**Comment by shauru1118** [comment]
Моя программа возвращает только {"error":"...", и там написано, что введено неправильное выражение, проверь его. Так же все расшифровки написаны в README, посмотри там.

**Comment by shauru1118** [comment]
> ![image](https://private-user-images.githubusercontent.com/134312352/398254632-a0926e7e-3e99-47bc-89d7-b985b83e9e3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNjI5NDUsIm5iZiI6MTczNTA2MjY0NSwicGF0aCI6Ii8xMzQzMTIzNTIvMzk4MjU0NjMyLWEwOTI2ZTdlLTNlOTktNDdiYy04OWQ3LWI5ODViODNlOWUzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQxNzUwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2E5YmFkYWVjOThhMmMzNjU3YjllNjEzMGFiNzgxNzA2ZGE1ODRhMTQ0MjZjYTc3ODM1MTc2ZmZjNDA2YmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.95TCP3nbBGD-CASSLa8ABijVhaHQm4V3xonIjlJkh_0) И как понять в чем ошибка...

Моя программа возвращает только {"error":"...", и там написано, что введено неправильное выражение, проверь его. Так же все расшифровки написаны в README, посмотри там.
